#!/bin/bash
set -e

# Name of the gadget
GADGET_DIR=/sys/kernel/config/usb_gadget/virtex
UDC=$(ls /sys/class/udc | head -n 1)

# Clean up any existing gadget
if [ -d "$GADGET_DIR" ]; then
    echo "Cleaning up old gadget..."
    echo "" > "$GADGET_DIR/UDC" || true
    rm -f "$GADGET_DIR/configs/c.1/hid.usb"*
    rmdir "$GADGET_DIR/functions/hid.usb0" "$GADGET_DIR/functions/hid.usb1" 2>/dev/null || true
    rmdir "$GADGET_DIR/configs/c.1/strings/0x409" "$GADGET_DIR/configs/c.1" 2>/dev/null || true
    rmdir "$GADGET_DIR/strings/0x409" "$GADGET_DIR"
fi

echo "Setting up composite USB gadget (Keyboard + Mouse)..."
mkdir -p "$GADGET_DIR"
cd "$GADGET_DIR"

# USB Device identifiers
echo 0x1d6b > idVendor    # Linux Foundation
echo 0x0104 > idProduct   # Multifunction Composite Gadget
echo 0x0100 > bcdDevice
echo 0x0200 > bcdUSB

# Strings
mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "Andrew Munro" > strings/0x409/manufacturer
echo "Virtex USB HID Bridge" > strings/0x409/product

# Configuration
mkdir -p configs/c.1/strings/0x409
echo "Config 1: HID composite" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

####################################
# HID Keyboard Function
####################################
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol   # Keyboard
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne '\x05\x01\x09\x06\xa1\x01\x05\x07\x19\xe0\x29\xe7\x15\x00\x25\x01\x75\x01\x95\x08\x81\x02\x95\x01\x75\x08\x81\x03\x95\x05\x75\x01\x05\x08\x19\x01\x29\x05\x91\x02\x95\x01\x75\x03\x91\x03\x95\x06\x75\x08\x15\x00\x25\x65\x05\x07\x19\x00\x29\x65\x81\x00\xc0' > functions/hid.usb0/report_desc

####################################
# HID Mouse Function
####################################
mkdir -p functions/hid.usb1
echo 2 > functions/hid.usb1/protocol   # Mouse
echo 1 > functions/hid.usb1/subclass
echo 3 > functions/hid.usb1/report_length
echo -ne '\x05\x01\x09\x02\xa1\x01\x09\x01\xa1\x00\x05\x09\x19\x01\x29\x03\x15\x00\x25\x01\x95\x03\x75\x01\x81\x02\x95\x01\x75\x05\x81\x03\x05\x01\x09\x30\x09\x31\x15\x81\x25\x7f\x75\x08\x95\x02\x81\x06\xc0\xc0' > functions/hid.usb1/report_desc

# Link both functions to config
ln -s functions/hid.usb0 configs/c.1/
ln -s functions/hid.usb1 configs/c.1/

# Bind to UDC (activates the gadget)
echo "$UDC" > UDC

echo "Composite HID (keyboard + mouse) gadget activated."
